# Generated by Django 4.0 on 2021-12-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('ima', models.ImageField(upload_to='F:/PPP_porject/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
