# Generated by Django 4.0 on 2021-12-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portflio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ima',
            new_name='image',
        ),
    ]
