# Generated by Django 4.0 on 2021-12-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portflio', '0002_rename_desc_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portflio/images/'),
        ),
    ]
